exchanges:
  - binance:
      - code: eth_usdt
        pair:
          base: ETH
          quote: USDT
      - code: btc_usdt
        pair:
          base: BTC
          quote: USDT
  - dfinance-test:
      - code: dfi_eth
        pair:
          base: dfi
          quote: eth
        simulate:
          enabled: true
          min_price: 869000.0
          max_price: 871000.0
          period_s: 1
      - code: dfi_btc
        pair:
          base: dfi
          quote: btc
        simulate:
          enabled: true
          min_price: 18000.0
          max_price: 20000.0
          period_s: 1
