exchanges:
  - binance:
      - code: eth_usdt
        pair:
          base: ETH
          quote: USDT
      - code: btc_usdt
        pair:
          base: BTC
          quote: USDT
  - wings:
      - code: wings_eth
        pair:
          base: wings
          quote: eth
      - code: eth_wings
        pair:
          base: eth
          quote: wings
