exchanges:
  - binance:
      - code: eth_usdt
        pair:
          base: ETH
          quote: USDT
      - code: btc_usdt
        pair:
          base: BTC
          quote: USDT
  - dfinance:
      - code: dfi_eth
        pair:
          base: dfi
          quote: eth
      - code: eth_dfi
        pair:
          base: eth
          quote: dfi
