name: Tests & CrossBuild & DockerBuild

# on: [push, pull_request]
on:
  push:
    # branches:
    #   - master
    #   - feature-*
    # tags:
    #   - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
  #   branches:
  #     - master
  #     - feature-*
  #   tags:
  #     - v[0-9]+.[0-9]+.[0-9]+

jobs:
  test-build:
    name: Tests & CrossBuild
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.14.1
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/github.com/${{ github.repository }}

    - name: Set GOPATH
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Make binaries for integration tests
      run: |
        make

    - name: Run UNIT tests
      run: |
        go test ./... --tags=unit

    - name: Run CLI tests
      run: |
        go test ./... --tags=cli

    - name: Run REST tests
      run: |
        go test ./... --tags=rest

    - name: Run INTEG tests
      run: |
        docker login -u ${OWN_REGISTRY_USR} --password-stdin ${REGISTRY} <<< ${OWN_REGISTRY_PWD}
        docker image pull ${REGISTRY}/dfinance/dvm:${DVM_TAG}
        go test ./... --tags=integ
        docker logout
      env:
        DVM_TAG: ${{ secrets.DVM_TAG }}
        REGISTRY: ${{ secrets.OWN_REGISTRY }}
        OWN_REGISTRY_USR: ${{ secrets.OWN_REGISTRY_USR }}
        OWN_REGISTRY_PWD: ${{ secrets.OWN_REGISTRY_PWD }}

    - name: Make binaries crossbuild
      run: make binaries

    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          builds/dncli-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  docker-build:
    name: Docker Build
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: '[OwnRegistry] Build and push docker image'
      uses: dfinance/gh-actions@master
      with:
        name: registry.wings.toys/dfinance/dnode
        username: ${{ secrets.OWN_REGISTRY_USR }}
        password: ${{ secrets.OWN_REGISTRY_PWD }}
        dockerfile: ./.build/Dockerfile
        build_params: --build-arg CI_PIPELINE_ID=${GITHUB_RUN_ID} --build-arg CI_COMMIT_REF_NAME=${GITHUB_REF} --build-arg CI_COMMIT_SHA=${GITHUB_SHA}
        registry: registry.wings.toys
        cache: true

    - name: '[DockerHub] Build and push docker image'
      uses: dfinance/gh-actions@master
      # if: success() && startsWith(github.ref, 'refs/tags/')
      with:
        name: dfinance/dnode
        username: ${{ secrets.DH_REGISTRY_USR }}
        password: ${{ secrets.DH_REGISTRY_PWD }}
        dockerfile: ./.build/Dockerfile
        build_params: --build-arg CI_PIPELINE_ID=${GITHUB_RUN_ID} --build-arg CI_COMMIT_REF_NAME=${GITHUB_REF} --build-arg CI_COMMIT_SHA=${GITHUB_SHA}
        cache: true
